module.exports = {
  config: {
    fontSize: 14,
    fontFamily: '"Monolisa", "Fira Code", Menlo, "DejaVu Sans Mono", "Lucida Console", monospace',
    cursorColor: 'rgba(248,28,229,0.8)',
    cursorShape: 'BLOCK',
    foregroundColor: '#fff',
    backgroundColor: 'rgba(0, 0, 0)',
    borderColor: '#333',
    css: '',
    termCSS: '',
    showHamburgerMenu: '',
    showWindowControls: '',
    padding: '12px 14px',
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff',
    },
    env: { TERM: 'cygwin' },
    bell: 'SOUND',
    copyOnSelect: false,
    /**
     * Uncomment below lines for windows
     */
    //  shell: 'C:\\Users\\ritik\\AppData\\Local\\Microsoft\\WindowsApps\\debian.exe',
    //  shellArgs: [],
  },
  plugins: ['hyperborder', 'hyper-tab-icons', "hyper-opacity", "hyperpower"],
  localPlugins: [],
};
